[package]
name = "cronpro"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.12", features = ["tokio"] }
webbrowser = "0.8"
chrono = "0.4"
tokio = { version = "1.38", features = ["rt", "time"] }